version: "3.4"
services:
  app:
    container_name: nim
    build:
      context: ./server/
      dockerfile: Dockerfile
    tty: true
    privileged: true
    volumes:
      - ./server/volume:/opt/nim/server
    ports:
      - 5000:5000
